services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USERNAME}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
#  backend:
#    image: server
#    restart: no
#    environment:
#      POSTGRES_URL: ${DATABASE_URL}
#      POSTGRES_USERNAME: ${DATABASE_USER}
#      POSTGRES_PASSWORD: ${DATABASE_PASS}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresql
#    env_file:
#      - .env
volumes:
  database: