[versions]

paper = "1.21.8-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
adventure = "4.24.0"
papi = "2.11.6"
jackson  = "2.17.3"
guava = "33.5.0-jre"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
papi = { group = "me.clip", name = "placeholderapi", version.ref = "papi" }
jackson = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }